server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
logging:
  file:
    name: ${LOGS_FILE_NAME}
    path: ${LOGS_PATH}
  level:
    com.danilomontoya: ${LOGS_LEVEL}
